[package]
name = "heisensim-intercept"
description = "Syscall interception layer for heisensim (vDSO trampoline, ptrace, seccomp-BPF)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
heisensim-core.workspace = true
nix.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
goblin = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
memmap2 = "0.9"
