[package]
name = "heisensim"
description = "The Heisenbug Simulator — deterministic chaos testing for Kubernetes"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "heisensim"
path = "src/main.rs"

[dependencies]
heisensim-core.workspace = true
heisensim-timeline.workspace = true
heisensim-probe.workspace = true
heisensim-k8s.workspace = true
heisensim-fault.workspace = true
heisensim-props.workspace = true
heisensim-intercept.workspace = true
heisensim-diverge.workspace = true
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
rand.workspace = true
uuid.workspace = true
kube.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
tracing-opentelemetry.workspace = true
tempfile = "3"
xxhash-rust.workspace = true
reqwest.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
